apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s90eo4y4p-java-quarkus
  janus-idp.io/tekton: s90eo4y4p-java-quarkus
  backstage.io/kubernetes-id: s90eo4y4p-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s90eo4y4p-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
